name: ControlGRIS CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  Build-Ubuntu-20-04:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
      - name: Install required packages
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export TZ=Etc/UTC
          apt-get update
          apt-get install -y git curl unzip sudo wget lsb-release software-properties-common make build-essential tzdata

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install latest Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          ./llvm.sh 18
          apt-get install -y clang-18


      - name: Install dependencies # taken from https://github.com/juce-framework/JUCE/blob/develop/docs/Linux%20Dependencies.md
        run: |
          apt-get install -y ladspa-sdk freeglut3-dev libasound2-dev libcurl4-openssl-dev libfreetype6-dev \
              libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev libjack-jackd2-dev \
              libfontconfig1-dev libx11-dev libxext-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev

      - name: Build Projucer
        run: make -C submodules/StructGRIS/submodules/JUCE/extras/Projucer/Builds/LinuxMakefile CXX=clang++-18 -j$(nproc)

      - name: Generate makefile (Standalone & VST3 only)
        run: |
          cd JUCE
          submodules/StructGRIS/submodules/JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer --resave ../ControlGRIS.jucer --set-exporter LinuxMakefile --set-config Release --set-enabled-targets Standalone,VST3

      - name: Compile ControlGRIS (Standalone & VST3 only)
        run: |
          cd Builds/LinuxMakefile
          make CXX=clang++-18 CONFIG=Release -j8 Standalone VST3

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ControlGRIS-Build
          path: Builds/LinuxMakefile/build/*

  Build-macOS:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Projucer
        run: |
          cd submodules/StructGRIS/submodules/JUCE/extras/Projucer/Builds/MacOSX
          xcodebuild -project Projucer.xcodeproj \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Generate Xcode project
        run: |
          chmod +x submodules/StructGRIS/submodules/JUCE/extras/Projucer/Builds/MacOSX/build/Release/Projucer.app/Contents/MacOS/Projucer
          submodules/StructGRIS/submodules/JUCE/extras/Projucer/Builds/MacOSX/build/Release/Projucer.app/Contents/MacOS/Projucer --resave ControlGRIS.jucer

      - name: build all formats (Standalone, VST3, AU) for arm64 and x86_64
        run: |
          formats=("Standalone Plugin" "VST3" "AU")

          for format in "${formats[@]}"; do
            safeFormat=$(echo "$format" | tr ' ' '-')
            echo "Building universal binary for $format..."

            # the INSTALL_PATH and DSTROOT options are used to avoid installing the AU/VST plugins to the system
            xcodebuild -project Builds/MacOSX/ControlGRIS.xcodeproj \
                      -scheme "ControlGRIS - $format" \
                      -configuration Release \
                      -destination 'platform=macOS' \
                      CONFIGURATION_BUILD_DIR=Builds/MacOSX/output/${safeFormat}-universal \
                      MACOSX_DEPLOYMENT_TARGET=10.13 \
                      ARCHS="arm64 x86_64" \
                      INSTALL_PATH=/tmp/fakeInstall \
                      DSTROOT=/tmp/fakeInstallRoot \
                      build
          done

      - name: good ol ls -R
        run: ls -R

      - name: Prepare plugin artifacts for upload
        run: |
          mkdir -p macOS
          find /tmp/fakeInstallRoot -name "*.vst3" -exec cp -R {} macOS/ \;
          find /tmp/fakeInstallRoot -name "*.component" -exec cp -R {} macOS/ \;
          find /tmp/fakeInstallRoot -name "*.app" -exec cp -R {} macOS/ \;
          cp -R Builds/MacOSX/Builds/MacOSX/output/Standalone-Plugin-universal/ControlGRIS.app macOS/ || true

      - name: Upload macOS builds
        uses: actions/upload-artifact@v4
        with:
          name: ControlGRIS-macOS
          path: macOS/*
          if-no-files-found: error

  Build-Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Projucer
        run: |
          cd submodules/StructGRIS/submodules/JUCE/extras/Projucer/Builds/VisualStudio2022
          msbuild Projucer.sln /p:Configuration=Release /p:Platform=x64 /p:WarningsAsErrors=False

      - name: Generate Visual Studio project
        run: |
          submodules/StructGRIS/submodules/JUCE/extras/Projucer/Builds/VisualStudio2022/x64/Release/App/Projucer.exe --resave ControlGRIS.jucer

      - name: Remove VST3 copy step from .vcxproj #this copy step is useless on the pipeline, and causes it to fail
        run: sed -i '/<PostBuildEvent>/,/<\/PostBuildEvent>/d' Builds/VisualStudio2022/ControlGRIS_VST3.vcxproj
        shell: bash

      - name: build shared code
        run: msbuild Builds/VisualStudio2022/ControlGRIS_SharedCode.vcxproj -p:Configuration=Release -p:Platform=x64

      - name: build standalone
        run: msbuild Builds/VisualStudio2022/ControlGRIS_StandalonePlugin.vcxproj -p:Configuration=Release -p:Platform=x64

      - name: build VST3
        run: msbuild Builds/VisualStudio2022/ControlGRIS_VST3.vcxproj -p:Configuration=Release -p:Platform=x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ControlGRIS-Build-Windows
          path: |
            Builds/VisualStudio2022/x64/Release/**/*.vst3
            Builds/VisualStudio2022/x64/Release/**/*.exe
